openapi: 3.0.3
info:
  title: LegalMente AI™'s API Documentation
  description: |
    <b>LegalMente AI™</b> is an AI platform that helps with contract reviews using our <b>RedFlag Detection AI</b>, answers questions through our AI Paralegal, **Para**,  supports LLC and Corporation formation, offers legal document templates, and connects you with affordable licensed attorneys.
    <br></br>
      This is the official API Documentation for **RedFlag Detection AI** (for Business Associate Agreement (BAA), Non-Disclosure Agreement (NDA) & Simple Agreement for Future Equity (SAFE)) & **Para** (AI Paralegal assistant) APIs that powers on [LegalMente AI™](https://legalmente.ai/).
      
    ----
    <br>**Quick Guide:**
    | Access | Instructions |
    |------|-------------|
    | **To get API Key**|  Select the "**https://lm-redflag-detection-ai.azurewebsites.net/** - Base URL for SAFE/NDA/BAA review automation and to get API Key" from the '**Servers**' dropdown and then send a POST request through "**/get_api_key**" path. |
    | **To access Simple Agreement for Future Equity (SAFE), Business Associate Agreement (BAA) & Non-Disclosure Agreement (NDA) RedFlag Detection™ AI API**|  Select the "**https://lm-redflag-detection-ai.azurewebsites.net/** - Base URL for SAFE/NDA/BAA review automation and to get API Key" from the '**Servers**' dropdown and then send a POST request through "**/document_response**" path. |
    | **To access Para General and Para Document**|  Select the "**https://lm-para-assistant.azurewebsites.net/** - Base URL to access Para General and Para Document" from the '**Servers**' dropdown and then send a POST request through "**/ai_response**" path. |</br>
    
    ----
    **RedFlag Detection™ AI** uses a legal playbook similar to what a lawyer would follow, pinpointing any potential issues in NDA, SAFE, and BAA contracts.
    
    **RedFlag Detection™ AI's Output Parameters:**
    | Output Component  | Description                                                        | Output Format |
    |-------------------|--------------------------------------------------------------------|------|
    | AI_Decision       | Decision made by AI regarding the checklist's validity in the Contract. [Pass, Fail, Neutral] | string |
    | AI_Message        | A brief, AI-generated message explaining why a clause/statement in the Contract is acceptable, re-negotiable, or has a neutral informational opinion for each of the review categories. | string|
    | Alert_Type        | These are the different review categories for a contract based on the Lawyer's playbook. | string |
    | Page_Number       | Page number(s) of the relevant text in the document. | integer |
    | Text_To_Highlight | Specific text where AI highlighted the issue.  | string |
    
    ----
    **Para™** is AI Paralegal assistant that is built to answer general or legal inquiries but does not give any legal advice.
    <br>**Features of Para™:**
      * **Para™ General:** Assists with general and legal inquiries. Visit it on the [LegalMente AI™ Home Page](https://app.legalmente.ai/home).
      * **Para™ Document:** Should be integrated with RedFlag Detection™ AI to address inquires related to contracts uploaded via the RedFlag Detection™ AI API. This can be found on the Document Alerts Page after you upload your contract into the [LegalMente AI™ RedFlag Detection™ AI](https://app.legalmente.ai/home).
      * **Para™ Business Formation:** This feature works with the Business Formation Form to guide users by explaining each field clearly and answering questions about forming an LLC or Corporation. Access it on the [LegalMente AI™ AI Augmented Business Formation](https://app.legalmente.ai/llc/entityinfo) page.
    </br>
    
    **Para™ General and Para™ Document Output Parameters:**
    | Output Component  | Description                                                        | Output Format | Additional Information |
    |-------------------|--------------------------------------------------------------------|------|------|
    | user_id       | A unique ID assigned to each user interacting with Para™ ensures context and continuity across multiple interactions.  | integer | Available through Para™ General and Para™ Document Output Response. |
    | user_input    | Refers to the text or message entered by the user that Para receives and processes. | string |Available through Para™ General and Para™ Document Output Response.  |
    | url | The URL where the document can be accessed.  | string | Available through Para™ General and Para™ Document Output Response. |
    | answer | Response from Para™ based on the user_input. | string | Available through Para™ General and Para™ Document Output Response. |
    | recommendation | Provides attorney recommendation based on user input. This feature appears only when Para™ determines that an attorney is needed based on the user’s inquiry, else shows "". | string |Available through Para™ General Output Response. |
    | metadata | A JSON object containing multiple arrays that specify the sources Para™ referenced to generate the response. | json |Available through Para™ Document Output Response. |
    
    ----
    <br>
    
  contact:
    email: douglas@legalmente.ai
  version: 2.0.0
externalDocs:
  description: Find out more about LegalMente AI
  url: https://legalmente.ai/
servers:
- url: https://lm-redflag-detection-ai.azurewebsites.net/
  description: Base URL for SAFE/NDA/BAA review automation and to get API Key
- url: https://lm-para-assistant.azurewebsites.net/
  description: Base URL to access Para General and Para Document
paths:
  /get_api_key:
    post:
      tags:
      - First Step, to get API Key.
      description: |
        The first step is using this API to obtain an API key, which you'll use to access the RedFlag Detection AI and Para APIs.
        
        -----
        **Important Note:**
        _The 'User ID' should be 'Swagger-{Your Company Name}'. Example: 'Swagger-UnitedHealth Group'._
        
        ----
        **Input Parameters:**
        | Component  | Description                                                        | Input format | Field Requirement |
        |-------------------|-------------------------------------------------------------|--------------|-------------------|
        | User ID        | 'Swagger-{Your Company Name}' | string | Required |
        
        ----
        ***If you see a **"Failed to fetch"** error, select the appropriate server from the Servers dropdown as described above.*
        
      operationId: getapikey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                User ID:
                  type: string
                  description: User ID
                  example: "Swagger-UnitedHealth Group"
      responses:
        '200':
          description: Returns the mapped API Key required for further authentication.
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
                    description: api_key.
        '400':
          description: Bad request when the input structure is not correct or missing
            required fields.
        '500':
          description: Internal server error indicating issues with server-side processing.
  /document_response:
    post:
      tags:
      - RedFlag Detection AI API for Simple Agreement for Future Equity (SAFE), Business Associate Agreement (BAA) & Non-Disclosure Agreement (NDA)
      description: |
        This automated review process checks if the provided PDF is a valid
        SAFE/NDA/BAA; if so, it returns AI alerts; otherwise, it responds with "invalid document". 
        ----
        All PDFs are currently accessed via Web-accessible URL.
        
        ----
        **SAFE/NDA/BAA RedFlag Detection AI's Input Parameters:**
        | Component  | Description | Input format | Field Requirement | Acceptable Values |
        |---------|-----------|------|------|------|
        | rfd_id        | Specifies the type of contract to review | string | Required | nda (to access NDA Contract), baa (to access baa contract), safe (to access safe contract)|
        | api_key       | Authorization key | string | Required | retrive from "/get_api_key" endpoint|
        | url           | The URL where the document is accessible | string | Required | (URL to the document) |
        | entity_type   | Depends on the rfd_id: >For nda: "discloser" or "receiver"; >For baa: "covered entity" or "business associate"; >For safe: "Investor" or "Company";  | string | Required | discloser, receiver, covered entity, business associate, Investor, Company |
        | entity_name   | The name of the party involved in the contract; this is optional | string | Required | Name of the entity|
        | nda_type      | Applicable only for nda; it specifies whether the contract pertains to "healthcare" or "non Healthcare" | string | Required | healthcare, non Healthcare |
        
        _*While **'entity_name'** is optional, including it will improve accuracy._

        ----
        _Refer the "RedFlag Detection AI's Output Parameters" above for output description._
        
        ----
        ***If you see a **"Failed to fetch"** error, select the appropriate server from the Servers dropdown as described above.*
        
      operationId: documentresponse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rfd_id:
                  type: string
                  description: rfd_id
                  example: nda
                api_key:
                  type: string
                  description: api_key
                  example: provide your api_key here
                url:
                  type: string
                  description: url
                  example: https://www.dropbox.com/scl/fi/fcjg4ysmjssm2398c3wur/sample1-Non-Disclosure-Agreement-VA.pdf?rlkey=ridizufrnreepy958yzj3l6ll&st=8bts2nmh&dl=1
                entity_type:
                  type: string
                  description: entity_type
                  example: discloser
                entity_name:
                  type: string
                  description: entity_name
                  example: swagger-test
                nda_type:
                  type: string
                  description: nda_type
                  example: non Healthcare
                
      responses:
        '200':
          description: Returns the evaluation results of the SAFE/NDA/BAA contracts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  AI_Decision:
                    type: string
                    description: Decision made by AI regarding the checklist's validity in the Contract. [Pass, Fail, Neutral]
                  AI_Message:
                    type: string
                    description:   Message depending with respect to AI_Decision.
                  Alert_Type:
                    type: string
                    description:   Name of the Alerts for each category in Jose's Playbook.
                  Page_Number:
                    type: integer
                    description:   Page number(s) of the relevant text in the document.
                  Text_To_Highlight:
                    type: string
                    description: Specific text where AI highlighted the issue.
        '400':
          description: Bad request when the input structure is not correct or missing
            required fields.
        '500':
          description: Internal server error indicating issues with server-side processing.
  /ai_response:
    post:
      tags:
      - Para APIs (Para General & Para Document)
      description: |
        This AI Paralegal assistant helps with user inquiries, whether they are general, legal, or related to RedFlag Detection AI contract reviews. 
        
        ----
        All PDFs are currently accessed via Web-accessible URL.
        
        ----
        **Para General and Para Document Input Parameters:**
        | Component  | Description | Input format | Field Requirement | Acceptable Values |
        |---------|-----------|------|------|------|
        | user_id | Unique ID that identifies each user interacting with Para™. This will help us maintain context and continuity across multiple interactions. | integer | Required | Example: 111, 234|
        | api_key| Authorization key | string | Required | retrive from "/get_api_key" endpoint|
        | para_type| Specific Para™ sub-division to be accessed. | string | Required | general,document |
        | user_input         | Refers to the text or message entered by the user, which the Para receives and processes. | string | Required | Example: “Summarize the attached Document.”| 
        | url         | The URL where the document is accessible. | string | Optional when para_type="general"; Required when para_type="document"  | should be provided when integrated with RedFlag Detection AI or when user has any inquiry about a document | 
        | chat_history     | This is JSON object containing multiple historical user_input and answer from previous conversation. | json | Required | when no history: [];|

        ----
        _Refer the "Para™ General and Para™ Document Output Parameters" above for output description._

        ----
        ***If you see a **"Failed to fetch"** error, select the appropriate server from the Servers dropdown as described above.*
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: user_id
                  example: 1
                api_key:
                  type: string
                  description: api_key
                  example: provide your api_key here
                para_type:
                  type: string
                  description: para_type
                  example: general
                user_input:
                  type: string
                  description: user_input
                  example: Summarize the document
                url:
                  type: string
                  description: url
                  example: https://www.dropbox.com/scl/fi/fcjg4ysmjssm2398c3wur/sample1-Non-Disclosure-Agreement-VA.pdf?rlkey=ridizufrnreepy958yzj3l6ll&st=8bts2nmh&dl=1
                chat_history:
                  type: object
                  description: chat_history
                  example: []
      responses:
        '200':
          description: Returns response from Para APIs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    description: user_id.
                  user_input:
                    type: string
                    description: user_input
                  url:
                    type: string
                    description: url
                  answer:
                    type: string
                    description: answer
                  recommendation:
                    type: string
                    description: recommendation
        '400':
          description: Bad request when the input structure is not correct.
        '500':
          description: Internal server error.

